//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laminatsia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int ID { get; set; }
        public int ID_ColourGoods { get; set; }
        public System.DateTime DateComing { get; set; }
        public string Profile { get; set; }
        public string City { get; set; }
        public string Dealer { get; set; }
        public string Notes { get; set; }
        public byte Counts { get; set; }
        public string Colour { get; set; }
        public System.DateTime DateToWork { get; set; }
        public string StatusProfile { get; set; }
        public System.DateTime DateReady { get; set; }
        public string StatusGoods { get; set; }
        public string Action { get; set; }
        public string UserName { get; set; }
        public System.DateTime DataTimeChange { get; set; }
    }
}
