//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laminatsia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColourGoods
    {
        public int ID { get; set; }
        public System.DateTime DateComming { get; set; }
        public int Profile_ID { get; set; }
        public int Dealer_ID { get; set; }
        public string Notes { get; set; }
        public byte Counts { get; set; }
        public int Colour_ID { get; set; }
        public System.DateTime DateToWork { get; set; }
        public bool StatusProfile { get; set; }
        public System.DateTime DateReady { get; set; }
        public bool StatusGoods { get; set; }
    
        public virtual ColourProfile ColourProfile { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
